# Generated by Django 3.0.7 on 2020-06-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_players', models.IntegerField(default=2)),
                ('game_id', models.CharField(default='jX1E2M2M6rhDbnYa', max_length=16)),
            ],
        ),
    ]
