# Generated by Django 3.0.7 on 2020-06-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(default='huCfVBEmfNPnxnRI', max_length=16, unique=True),
        ),
    ]
