# Generated by Django 3.0.7 on 2020-06-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20200618_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='num_of_players',
        ),
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(default='OQ3TQqPoZTz8HJrV', max_length=16, unique=True),
        ),
    ]
