# Generated by Django 3.0.7 on 2020-06-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_auto_20200619_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(),
        ),
    ]
