# Generated by Django 3.0.5 on 2020-06-23 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20200619_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
